name=input("What is your name?")
age=input("How old are you?")
height= input("How tall are you?")
print(f"My name is {name}.")
print(f"I am {age} years old, and my height is {height} cm.")
age=int(age)
print(f"In 6 years I will be {age+6} years old.")